const JOURNEY_DETAILS = {
    title: 'JOURNEY DETAILS REPORT',
    description: 'JOURNEY DETAILS REPORT DOWNLOAD',
    type: 2,
}

const INSPECTION_DETAILS = {
    title: 'INSPECTION DETAILS REPORT',
    description: 'INSPECTION DETAILS REPORT DOWNLOAD',
    type: 1,
}

module.exports = { JOURNEY_DETAILS, INSPECTION_DETAILS  }
